version: "3.2"
services:
    bnfTicker:
        container_name: bnfTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_bnf.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'

    btcTicker:
        container_name: btcTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_btc.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'

    djiTicker:
        container_name: djiTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_dji.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'
    
    niftyTicker:
        container_name: niftyTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_nifty.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'
    
    sgxTicker:
        container_name: sgxTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_sgx.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'
    
    vixTicker:
        container_name: vixTicker
        image: 'shashankullas/tickerbot:1.0.3'
        restart: always
        environment:
            - CONFIG_FILE=config_vix.ini
        deploy:
          resources:
            limits:
              memory: 64M
              cpus: '0.1'
            reservations:
              memory: 32M
              cpus: '0.02'
